networks:
  default:
    driver: bridge
    name: roboshop
    #external: true
services:
  mongodb:
    image: lakshmi1092/mongodb:v1
    container_name: mongodb
  catalogue:
    image: lakshmi1092/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: lakshmi1092/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: lakshmi1092/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: lakshmi1092/mysql:v1
    container_name: mysql
  shipping:
    image: lakshmi1092/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASSWORD: roboshop123
  payment:
    image: lakshmi1092/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
      - cart
      - user
      - rabbitmq
  frontend:
    image: lakshmi1092/frontend:v1
    container_name: frontend
    ports:
      - "80:80" #host and conatiner port
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
      - cart