FROM node:20-alpine3.21

WORKDIR /opt/server

COPY package.json .
COPY *.js .

RUN npm install

EXPOSE 8080

ENV MONGO="true"
ENV MONGO_URL="mongodb://mongodb:27017/catalogue"

CMD ["node", "server.js"]